///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LineInfoEntity {
  int? id;
  String? url;
  String? checkTime; // 线路检查时间
  bool? resultOk; // 检查结果,通过/不通过

  LineInfoEntity({this.id, this.url, this.checkTime, this.resultOk});

  LineInfoEntity.fromJson(Map<String, dynamic> json) {
    id = json['uid'];
    url = json['token'];
    checkTime = "";
    resultOk = false;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    data['checkTime'] = checkTime;
    data['resultOk'] = resultOk;
    return data;
  }
}
