///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserInfoEntity {
  int? uid;
  String? username;
  String? nickname;
  // 头像
  String? avatar;
  String? description;
  String? link;

  // 融云token
  String? token;
  // jwt访问token
  String? accessToken;
  // jwt刷新token
  String? refreshToken;
  // Bearer
  String? tokenType;
  // 过期时间
  int? expiresIn;

  UserInfoEntity({
    this.uid,
    this.username,
    this.token,
    this.nickname,
    this.accessToken,
    this.refreshToken,
    this.expiresIn,
    this.tokenType,
    this.avatar,
    this.description,
    this.link,
  });
  UserInfoEntity.fromJson(Map<String, dynamic> json) {
    uid = json['uid'];
    token = json['token'];
    username = json['username'];
    nickname = json['nickname'];
    avatar = json['avatar'];

    tokenType = json['tokenType'];
    expiresIn = json['expiresIn'];
    accessToken = json['accessToken'];
    refreshToken = json['refreshToken'];
    description = json['description'];
    link = json['link'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['uid'] = uid;
    data['username'] = username;
    data['nickname'] = nickname;
    data['avatar'] = avatar;

    data['token'] = token;

    data['tokenType'] = tokenType;
    data['expiresIn'] = expiresIn;
    data['accessToken'] = accessToken;
    data['refreshToken'] = refreshToken;
    data['description'] = description;
    data['link'] = link;

    return data;
  }
}
